# Generated by Django 4.2.3 on 2023-07-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
