# Generated by Django 4.2.3 on 2023-07-31 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualizer', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
